### ISSUE TITLE
Blink error after update

### ISSUE THREAD

**Issue by delonleo** [yerfor/GeneFacePlusPlus#47]
With the updated, unchanged code and settings, it appears that the eye cannot open.

https://github.com/yerfor/GeneFacePlusPlus/assets/104955548/f90a1bc4-6ee9-47fe-997b-751c351158e0

**Comment by yerfor** [comment]
Hi, have you re-train the model from scratch? 

Or this is probably caused by a hard coded eye_area_percent. I have update the inference code, and you can pull and try again.

**Comment by delonleo** [comment]
@yerfor Thank you for your response.

Updated the inference code with [98fa99265b6ca82bed97f3bd2b300ae80da4140f 
](https://github.com/yerfor/GeneFacePlusPlus/commit/98fa99265b6ca82bed97f3bd2b300ae80da4140f) but still face similar issue.

Trained from scratch. `Jae-in_head` seems ok.  Checkpoint 250,000 validation results for `frame_10138_sr.png` and `frame_1074_sr.png`. For e.g.
![frame_10138_sr](https://github.com/yerfor/GeneFacePlusPlus/assets/104955548/d5df924a-3066-4228-9641-529e419d6f9d)
![frame_10374_sr](https://github.com/yerfor/GeneFacePlusPlus/assets/104955548/0649ed99-4d55-4904-98f5-d1c61346d0a1)
But for `Jae-in_torso`, they are all with eyes closed.
![frame_10374_sr](https://github.com/yerfor/GeneFacePlusPlus/assets/104955548/5716ff2c-d6bb-4bc2-91a6-14dcf684b1a6)
![frame_9430_sr](https://github.com/yerfor/GeneFacePlusPlus/assets/104955548/9056bdc4-6336-4ce8-bafb-aa62ab2e46c7)

The config is:

```yaml
base_config:
  - ./lm3d_radnerf_torso.yaml

task_cls: tasks.radnerfs.radnerf_torso_sr.RADNeRFTorsoTask
head_model_dir: checkpoints/1007_radnerf_sr/lm3d_radnerf_sr
not_save_modules: ['criterion_lpips', 'dual_disc']
with_sr: true
torso_head_aware: true
individual_embedding_dim: 4
torso_individual_embedding_dim: 8 # 0 leads to worse image fidelity
smo_win_size: 3 # larger leads to oversmoothed lip

num_ckpt_keep: 1
lpips_mode: vgg19_v2 # alex | vgg19_v2 
lambda_lpips_loss: 0.001 # alex 0.001 | vgg19_v2 0.0001
lambda_ambient: 1. 
lambda_torso_deform: 0. # 1.0e-3 # L1 reg deformation torso, slight scale can improve stability
lambda_weights_entropy: 1.0e-4 # enlarge from 1e-4 leads to quick converged to 0

# the cause of NaN is the changed camera convention, the trans_z out of input scale of freqencoder.
# we change it into lm2ds and worked it out
sr_start_iters: 0_0000
lpips_start_iters: 20_0000
num_updates: 25_0000
clip_grad_norm: 0. # 1. in fp16 leads to nan
add_eye_blink_cond: true # to better control eye blink
eye_blink_dim: 4
```
Appreciate your advise on this issue.
